### ISSUE TITLE
When initially installing, the options cached TM dropdown is blank and UI elements inappropriately enabled

### ISSUE THREAD

**Issue by machawk1** [machawk1/Mink#174]
![screen shot 2015-12-15 at 4 46 45 pm](https://cloud.githubusercontent.com/assets/2514780/11825176/842a6976-a34b-11e5-9773-ebdb89da5624.png)

**Comment by machawk1** [comment]
Error in options console Mink options frame (not main Extensions page console):
```sh
Error in response to storage.get: TypeError: Cannot convert undefined or null to object
    at Object.callback (chrome-extension://ehlefgjpcinhloogfldmkojonnjpnloo/options.js:131:23)
    at HTMLDocument.populatedCachedTimeMapsUI (chrome-extension://ehlefgjpcinhloogfldmkojonnjpnloo/options.js:125:24)
```

**Comment by machawk1** [comment]
This is now fixed, @ibnesayeed.
