### ISSUE TITLE
Certain pages cause the UI to display incorrectly

### ISSUE THREAD

**Issue by machawk1** [machawk1/Mink#193]
Version 2.0. Per @weiglemc and @phonedude, trying to document this phenomena. MCW's screenshot:

![screen shot 2016-01-21 at 4 34 54 pm](https://cloud.githubusercontent.com/assets/2514780/12495536/379a9876-c05e-11e5-93fa-548fd8aa503c.png)

<pre>Ok, I'm having the behavior on my machine now - http://www.freemasonstreet.org/
(This was working so well that I wanted to check out and see if my church's website was archived.)

This worked fine the first time, but then after viewing a memento, I clicked the Mink icon to try to return to the live web and nothing happened, so I clicked the back button.  Then I tried the mink button again and got this.

Closed Chrome and restarted.  Same behavior.

And, going back to the URL after going to another one doesn't trigger Mink looking for mementos (icon doesn't change).

I think it's just getting into some weird state somehow.</pre>

I was able to replicate this on a new install. Content script console reads:
```sh
Error in response to storage.get: TypeError: Cannot read property 'length' of undefined
    at j (chrome-extension://jemoalkmipibchioofomhkgimhofbbem/js/jquery-2.1.1.min.js:2:26860)
    at Object.k.fireWith [as resolveWith] (chrome-extension://jemoalkmipibchioofomhkgimhofbbem/js/jquery-2.1.1.min.js:2:27673)
    at x (chrome-extension://jemoalkmipibchioofomhkgimhofbbem/js/jquery-2.1.1.min.js:4:11120)
    at XMLHttpRequest.<anonymous> (chrome-extension://jemoalkmipibchioofomhkgimhofbbem/js/jquery-2.1.1.min.js:4:14767)
```

More details to come.

**Comment by machawk1** [comment]
Clock does no animate, which indicates that the jquery invocation is prior to the animation timeouts starting.

**Comment by machawk1** [comment]
On the secondary run, assumably after caching has occurred:
```sh
Error in response to storage.get: TypeError: Cannot read property 'length' of undefined
    at displayUIBasedOnStoredTimeMap (chrome-extension://jemoalkmipibchioofomhkgimhofbbem/content.js:137:53)
    at Object.callback (chrome-extension://jemoalkmipibchioofomhkgimhofbbem/content.js:124:8)
    at displayUIBasedOnContext (chrome-extension://jemoalkmipibchioofomhkgimhofbbem/content.js:111:26)
    at Object.callback (chrome-extension://jemoalkmipibchioofomhkgimhofbbem/content.js:48:27)
```

**Comment by machawk1** [comment]
Reinstalled from source, same issue occurs and is reported in console. This is a Good Thing™.

**Comment by machawk1** [comment]
`http://www.freemasonstreet.org/` has this Link header in the response:
```sh
Link: <http://www.freemasonstreet.org/wp-json/>; rel="https://api.w.org/", <http://www.freemasonstreet.org/>; rel=shortlink
```
This is likely tripping up the memento detection code, which uses the Link header as a basis. Digging further...
