### ISSUE TITLE
File URIs are still processed and result in an exception

### ISSUE THREAD

**Issue by machawk1** [machawk1/Mink#217]
When accessing `file:///Users/me/.../picture.gif` in the browser, Mink produces 
``sh
Error in response to storage.get: TypeError: Cannot read property 'length' of undefined
    at Object.callback (chrome-extension://ffngamkphblhemlpabjfbgckjhlnhapg/content.js:109:46)
    at Object.callback (chrome-extension://ffngamkphblhemlpabjfbgckjhlnhapg/content.js:98:26)
``
on the content script (main window) console.

In `displayUIBasedOnContext()`:`for (var headerI = 0; headerI < headers.length; headerI++) `

1. File URIs should not be processed.
2. There ought to be a check to ensures headers exist before trying to iterate over them.

**Comment by machawk1** [comment]
Like resultant of `"matches": ["<all_urls>"],` in the manifest, which needs a `file://` exclusion.
